### PR TITLE
Ask to merge the article: How-to-add-additional-information-such-as-event-type-links-refund-policy-terms-and-conditions-and-code-of-conduct.md

### PR DESCRIPTION
**Pull request by bellaphan**

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please change all image filenames to start with "How-to-add-additional-information-". You can keep the specific info behind that. There is no problem with having long file names.

**Comment by mariobehling** [comment]
Still a few files to be changed and you need to update the images in the .md file.

**Comment by bellaphan** [comment]
Yes, I am doing it right now

**Review by mariobehling — APPROVED** [review]
Thank you!

**Pull request merged**
