### PR TITLE
Issue #161 How to add a sponsors listing to my event

### PR DESCRIPTION
**Pull request by Hackerbone**
I resolved the issue #161 . Renamed all images as in the contribution guidelines.
If all seems fine do merge ! 
Thanks.
@mariobehling @bellaphan

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please take out "Adding-sponsors" from the png names.

**Comment by Hackerbone** [comment]
Okay will do, I will leave it blank?

**Comment by Hackerbone** [comment]
@mariobehling changes done , pls merge if all seems fine also label it so that this gets accepted for Codeheat! Thanks

**Comment by mariobehling** [comment]
> Please take out "Adding-sponsors" from the png names.

e.g. How-to-add-sponsors-listing-to-my-event-Adding-sponsors-1.png -> How-to-add-sponsors-listing-to-my-event-1.png

**Comment by Hackerbone** [comment]
Oh alright ill just do it sorry !

**Comment by Hackerbone** [comment]
@mariobehling did the necessary changes! 
Review once and let me know if theres anything else to do. 
If all seems fine do label it with neccessary  tags for it to get accepted in codeheat

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
