### PR TITLE
How to schedule speakers and sessions

### PR DESCRIPTION
**Pull request by iamdevvalecha**
Schedule & Event Pages #74

### CODE REVIEW

**Comment by iamdevvalecha** [comment]
everything is okay just crop the images and try to use different email address

**Comment by iamdevvalecha** [comment]
@hpdang done! check this out.

**Comment by hpdang** [comment]
need a few more sample sessions to test the scheduler. At the end, show the schedule in the public page. Remove Step 6.

**Comment by iamdevvalecha** [comment]
a need to close this pr because need a few more sample sessions to test the schedule DATES WILL CONFLICT

**Comment by iamdevvalecha** [comment]
will solve this issue again

**Pull request closed without merging**
